apiVersion: batch/v1
kind: Job
metadata:
  name: create-test-accounts
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: create-test-accounts
          image: create-test-accounts-for-local-env:0.0.1
          env:
            - name: AUTH_API_URL
              value: "http://auth-api-nginx:30090/api/auth/login"
            - name: ACCOUNTS_API_URL
              value: "http://inner-circle-accounts-api-nginx:30090/api"            
            - name: SET_PASSWORD_URL
              value: "http://auth-api-nginx:30090/api/auth/set-password"